name: Github Pages
on:
  push:
    branches:
      - master
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      tags:
        description: 'tag' 
jobs:
  build-and-deploy:
    if: ${{ github.event.issue.number == 1 || github.event.issue.number == null }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Download bun
        run: |
          wget "https://github.com/oven-sh/bun/releases/download/bun-v0.1.5/bun-linux-x64.zip" -O bun_dir.zip
          unzip bun_dir.zip -d bun_dir
          mv ./bun_dir/bun-linux-x64/bun ./bun

      - name: Run mastodon script
        run: |
          ./bun install
          ./bun run build:feed

      - name: Download and Run Zola
        run: |
          wget "https://github.com/getzola/zola/releases/download/v0.16.0/zola-v0.16.0-x86_64-unknown-linux-gnu.tar.gz" -O zola.tar.gz
          tar -xf zola.tar.gz
          ./zola build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: public

      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: public
