name: deploy
env:
  ZOLA_VERSION: 0.15.3
on:
  push:
    branches:
      - master
  # issue_comment:
  #   types: [created]
  workflow_dispatch:
    inputs:
      tags:
        description: 'tag' 
jobs:
  build-and-deploy:
    if: ${{ github.event.issue.number == 1 || github.event.issue.number == null }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run mastodon script
        run: |
          npm install
          npm run build:feed

      - name: Download and Run Zola
        run: |
          wget "https://github.com/getzola/zola/releases/download/v$ZOLA_VERSION/zola-v$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz" -O zola.tar.gz
          tar -xf zola.tar.gz
          ./zola build

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public

      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: public
