name: Mirror and run GitLab CI

on:
  workflow_run:
    workflows: [Github Pages]
    types:
      - completed

jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'subfolder-gh-pages'

    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/kebg/kebg.gitlab.io"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "kebg"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "25756549"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
