name: Mirror and run GitLab CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description tag.'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/kebg/kebg.gitlab.io"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "kebg"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "25756549"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
