name: Deploy to neocities

# only run on changes to master
on:
  push:
    branches:
      - gh-pages

jobs:
  push-to-neocities:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # When the gh-pages is ready, deploy it to neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: .